# Generated by Django 3.0.5 on 2020-05-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200513_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='relation',
            field=models.CharField(help_text='friend, family', max_length=50, null=True),
        ),
    ]
